In [45]:
import pandas as pd
import random
import numpy as np
import itertools



# Define the number of rows in the dataset
num_rows = 1000

# Define possible values for each column
age_values = [random.randint(15, 70) for _ in range(num_rows)]
gender_values = [random.choice(['Male', 'Female']) for _ in range(num_rows)]
hair_type = [random.choice(['Straight', 'Wavy', 'Curvy']) for _ in range(num_rows)]
thickness = [random.choice(['Thin', 'Normal', 'Thick']) for _ in range(num_rows)]
hair_volume = [random.choice(['Low', 'Moderate', 'Volumized']) for _ in range(num_rows)]
scalp_feel = [random.choice(['Oily', 'Very Oily', 'Dry', 'Very Dry', 'Neither']) for _ in range(num_rows)]
hair_loss = [random.choice(['Few', 'Dozens', 'More']) for _ in range(num_rows)]
medications = [random.choice(['No', 'Not Sure', 'Yes']) for _ in range(num_rows)]
dandruff = [random.choice(['Yes', 'No']) for _ in range(num_rows)]
about_hair = [random.choice(['Very Exposed', 'Less Exposed', 'Not Exposed']) for _ in range(num_rows)]


In [47]:
hair_damage = []
scalp_damage = []
product_should_applied = []

for i in range(num_rows):
    # Calculate hair damage based on multiple factors
    if hair_loss[i] == 'Few':
        if medications[i] == 'No' and hair_type[i] in ['Straight', 'Wavy']:
            hair_damage.append('No/Mild')
        else:
            hair_damage.append('Mild/High')
    else:
        hair_damage.append('Very High')

    # Calculate scalp damage based on multiple factors
    if dandruff[i] == 'Yes':
        if scalp_feel[i] in ['Very Oily', 'Dry'] and hair_type[i] != 'Curvy':
            scalp_damage.append('Very High')
        else:
            scalp_damage.append('Mild')
    else:
        scalp_damage.append('No')
     
 # Recommend products based on hair and scalp condition
    if hair_damage[i] == 'Very High' and scalp_damage[i] == 'Very High':
        product_should_applied.append('Specialized Hair and Scalp Treatment Products')
    elif hair_damage[i] == 'Very High':
        product_should_applied.append('Specialized Hair Treatment Products')
    elif scalp_damage[i] == 'Very High':
        product_should_applied.append('Specialized Scalp Treatment Products')
    else:
        product_should_applied.append('Regular Hair and Scalp Care Products')

        

In [48]:
df = pd.DataFrame({
    'Age': age_values,
    'Gender': gender_values,
    'Hair Type': hair_type,
    'Thickness': thickness,
    'Volume': hair_volume,
    'Scalp': scalp_feel,
    'Hair Loss': hair_loss,
    'Medications': medications,
    'Dandruff': dandruff,
    'About Exposure': about_hair,
    'Hair Damage': hair_damage,
    'Scalp Damage': scalp_damage,
    'Product Applied': product_should_applied
})

# Display the first few rows of the dataset
print(df.head())

# Save the dataset to a CSV file
df.to_excel('HairMain.xlsx', index=False)

   Age  Gender Hair Type Thickness     Volume      Scalp Hair Loss  \
0   56  Female      Wavy    Normal        Low  Very Oily    Dozens   
1   70  Female     Curvy    Normal  Volumized        Dry    Dozens   
2   64    Male     Curvy    Normal  Volumized   Very Dry    Dozens   
3   37  Female  Straight      Thin        Low       Oily    Dozens   
4   29    Male  Straight      Thin  Volumized        Dry    Dozens   

  Medications Dandruff About Exposure Hair Damage Scalp Damage  \
0         Yes       No    Not Exposed   Very High           No   
1          No      Yes    Not Exposed   Very High         Mild   
2         Yes       No    Not Exposed   Very High           No   
3         Yes      Yes   Very Exposed   Very High         Mild   
4          No       No   Less Exposed   Very High           No   

                       Product Applied  
0  Specialized Hair Treatment Products  
1  Specialized Hair Treatment Products  
2  Specialized Hair Treatment Products  
3  Specialized Hai

In [49]:
import pandas as pd

In [50]:
data = pd.read_excel('HairMain.xlsx')
data

Age  Gender Hair Type Thickness     Volume      Scalp Hair Loss  \
0     56  Female      Wavy    Normal        Low  Very Oily    Dozens   
1     70  Female     Curvy    Normal  Volumized        Dry    Dozens   
2     64    Male     Curvy    Normal  Volumized   Very Dry    Dozens   
3     37  Female  Straight      Thin        Low       Oily    Dozens   
4     29    Male  Straight      Thin  Volumized        Dry    Dozens   
..   ...     ...       ...       ...        ...        ...       ...   
995   45    Male      Wavy      Thin        Low   Very Dry    Dozens   
996   70    Male     Curvy    Normal   Moderate    Neither      More   
997   40  Female      Wavy     Thick        Low    Neither       Few   
998   53  Female      Wavy     Thick   Moderate       Oily      More   
999   19    Male  Straight     Thick   Moderate        Dry      More   

    Medications Dandruff About Exposure Hair Damage Scalp Damage  \
0           Yes       No    Not Exposed   Very High           No   
1            No      Yes    Not Exposed   Very High         Mild   
2           Yes       No    Not Exposed   Very High           No   
3           Yes      Yes   Very Exposed   Very High         Mild   
4            No       No   Less Exposed   Very High           No   
..          ...      ...            ...         ...          ...   
995          No      Yes    Not Exposed   Very High         Mild   
996    Not Sure       No   Very Exposed   Very High           No   
997          No       No    Not Exposed     No/Mild           No   
998         Yes      Yes   Very Exposed   Very High         Mild   
999         Yes      Yes    Not Exposed   Very High    Very High   

                                   Product Applied  
0              Specialized Hair Treatment Products  
1              Specialized Hair Treatment Products  
2              Specialized Hair Treatment Products  
3              Specialized Hair Treatment Products  
4              Specialized Hair Treatment Products  
..                                             ...  
995            Specialized Hair Treatment Products  
996            Specialized Hair Treatment Products  
997           Regular Hair and Scalp Care Products  
998            Specialized Hair Treatment Products  
999  Specialized Hair and Scalp Treatment Products  

[1000 rows x 13 columns]

In [53]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])
data['Dandruff'] = le.fit_transform(data['Dandruff'])
df = pd.get_dummies(data, columns=['Hair Type', 'Thickness', 'Volume', 'Scalp', 'Hair Loss', 'Medications', 'About Exposure', 'Hair Damage', 'Scalp Damage', 'Product Applied'], prefix=['Hair Type', 'Thickness', 'Volume', 'Scalp', 'Hair Loss', 'Medications', 'About Exposure',  'Hair Damage', 'Scalp Damage', 'Product Applied'])
df

Age  Gender  Dandruff  Hair Type_Curvy  Hair Type_Straight  \
0     56       0         0            False               False   
1     70       0         1             True               False   
2     64       1         0             True               False   
3     37       0         1            False                True   
4     29       1         0            False                True   
..   ...     ...       ...              ...                 ...   
995   45       1         1            False               False   
996   70       1         0             True               False   
997   40       0         0            False               False   
998   53       0         1            False               False   
999   19       1         1            False                True   

     Hair Type_Wavy  Thickness_Normal  Thickness_Thick  Thickness_Thin  \
0              True              True            False           False   
1             False              True            False           False   
2             False              True            False           False   
3             False             False            False            True   
4             False             False            False            True   
..              ...               ...              ...             ...   
995            True             False            False            True   
996           False              True            False           False   
997            True             False             True           False   
998            True             False             True           False   
999           False             False             True           False   

     Volume_Low  ...  Hair Damage_Mild/High  Hair Damage_No/Mild  \
0          True  ...                  False                False   
1         False  ...                  False                False   
2         False  ...                  False                False   
3          True  ...                  False                False   
4         False  ...                  False                False   
..          ...  ...                    ...                  ...   
995        True  ...                  False                False   
996       False  ...                  False                False   
997        True  ...                  False                 True   
998       False  ...                  False                False   
999       False  ...                  False                False   

     Hair Damage_Very High  Scalp Damage_Mild  Scalp Damage_No  \
0                     True              False             True   
1                     True               True            False   
2                     True              False             True   
3                     True               True            False   
4                     True              False             True   
..                     ...                ...              ...   
995                   True               True            False   
996                   True              False             True   
997                  False              False             True   
998                   True               True            False   
999                   True              False            False   

     Scalp Damage_Very High  \
0                     False   
1                     False   
2                     False   
3                     False   
4                     False   
..                      ...   
995                   False   
996                   False   
997                   False   
998                   False   
999                    True   

     Product Applied_Regular Hair and Scalp Care Products  \
0                                                False      
1                                                False      
2                                                False      
3                                                False      
4                      

In [55]:
label_encoder = LabelEncoder()

# Apply Label Encoding to all columns in the DataFrame
df_encoded = df.apply(label_encoder.fit_transform)
df_encoded

Age  Gender  Dandruff  Hair Type_Curvy  Hair Type_Straight  \
0     41       0         0                0                   0   
1     55       0         1                1                   0   
2     49       1         0                1                   0   
3     22       0         1                0                   1   
4     14       1         0                0                   1   
..   ...     ...       ...              ...                 ...   
995   30       1         1                0                   0   
996   55       1         0                1                   0   
997   25       0         0                0                   0   
998   38       0         1                0                   0   
999    4       1         1                0                   1   

     Hair Type_Wavy  Thickness_Normal  Thickness_Thick  Thickness_Thin  \
0                 1                 1                0               0   
1                 0                 1                0               0   
2                 0                 1                0               0   
3                 0                 0                0               1   
4                 0                 0                0               1   
..              ...               ...              ...             ...   
995               1                 0                0               1   
996               0                 1                0               0   
997               1                 0                1               0   
998               1                 0                1               0   
999               0                 0                1               0   

     Volume_Low  ...  Hair Damage_Mild/High  Hair Damage_No/Mild  \
0             1  ...                      0                    0   
1             0  ...                      0                    0   
2             0  ...                      0                    0   
3             1  ...                      0                    0   
4             0  ...                      0                    0   
..          ...  ...                    ...                  ...   
995           1  ...                      0                    0   
996           0  ...                      0                    0   
997           1  ...                      0                    1   
998           0  ...                      0                    0   
999           0  ...                      0                    0   

     Hair Damage_Very High  Scalp Damage_Mild  Scalp Damage_No  \
0                        1                  0                1   
1                        1                  1                0   
2                        1                  0                1   
3                        1                  1                0   
4                        1                  0                1   
..                     ...                ...              ...   
995                      1                  1                0   
996                      1                  0                1   
997                      0                  0                1   
998                      1                  1                0   
999                      1                  0                0   

     Scalp Damage_Very High  \
0                         0   
1                         0   
2                         0   
3                         0   
4                         0   
..                      ...   
995                       0   
996                       0   
997                       0   
998                       0   
999                       1   

     Product Applied_Regular Hair and Scalp Care Products  \
0                                                    0      
1                                                    0      
2                                                    0      
3                                                    0      
4                      

In [56]:
x = df_encoded.iloc[:, 0:26].values
x[0]

array([41,  0,  0,  0,  0,  1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,
        1,  0,  0,  0,  0,  1,  0,  1,  0])

In [57]:
y = df_encoded.iloc[:, 26:].values
y

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0]])

In [58]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Load or prepare your dataset
# X contains input features
# y contains multivariate output variables

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Create a Multi-Output Decision Trees model
base_model = DecisionTreeRegressor()
model = MultiOutputRegressor(base_model)

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

print(y_pred)

[[0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]]


In [66]:
X_test[0]

array([50,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  1,
        1,  0,  0,  1,  0,  0,  0,  1,  0])

In [59]:
import pickle
pickle.dump(model,open('model_hair.pkl', 'wb'))

In [27]:
import itertools

value1 = ['Daily Maintainance', 'Oil Control', 'More Volume', 'Softness and Shine']

abc  = list(itertools.combinations(value1, 2))


In [46]:
# hair_goals = [random.choice([list(itertools.combinations(values, 3))]) for _ in range(num_rows)]
hair_goals = [random.choice(["'Daily Maintainance', 'Oil Control'", "'Daily Maintainance', 'More Volume'", "'Daily Maintainance', 'Softness and Shine'", "'Oil Control', 'More Volume'", "'Oil Control', 'Softness and Shine'", "'More Volume', 'Softness and Shine'"]) for _ in range(1000)]
