In [38]:
import pandas as pd
import random

# Define the number of rows in the dataset
num_rows = 1000

# Define possible values for each column
age_values = [random.randint(15, 65) for _ in range(num_rows)]
gender_values = [random.choice(['Male', 'Female']) for _ in range(num_rows)]
concerns_values = [random.choice(['Acne', 'Tan']) for _ in range(num_rows)]
dark_patches_values = [random.choice(['Yes', 'No']) for _ in range(num_rows)]
dark_spots_values = [random.choice(['No/Less Than 5', 'More Than 5']) for _ in range(num_rows)]
tanned_values = [random.choice(['Yes', 'No']) for _ in range(num_rows)]
fine_line_values = [random.choice(['No/Few', 'Deep']) for _ in range(num_rows)]
wrinkles_values = [random.choice(['Yes', 'No']) for _ in range(num_rows)]
beard_values = [random.choice(['Yes', 'No']) for _ in range(num_rows)]

# Predict skin attributes based on given criteria
sensitive_skin = []
skin_issues = []
primary_concern = []

for i in range(num_rows):
    if concerns_values[i] == 'Acne' and dark_patches_values[i] == 'Yes' and dark_spots_values[i] == 'More Than 5':
        sensitive_skin.append(1)
        skin_issues.append('Post-Inflammatory Hyperpigmentation - PIH and Acne')
        
    elif dark_spots_values[i]=='More Than 5' and tanned_values[i] == 'Yes':
        sensitive_skin.append(1)
        skin_issues.append('Hyperpigmentation and Tanning')
    
    elif tanned_values[i] == 1 and dark_patches_values[i] == 1:
        sensitive_skin.append(1)
        skin_issues.append('Psoriasis and Tanning')
        
        
    elif dark_patches_values[i] == 1 and dark_spots_values[i] == 2 and tanned_values[i] == 1:
        sensitive_skin.append(1)
        skin_issues.append('Eczema and Melasma and Tanning')
    
    elif dark_patches_values[i] == 1 and age_values[i] <= 25:
        sensitive_skin.append(1)
             
#     elif age_values[i]<=25 and wrinkles_values[i]=='Yes':
#         skin_issues.append('genetic and Tanning')
        
    else:
        sensitive_skin.append(0)
        skin_issues.append('No Issues')
        
np.size(skin_issues)


1000

In [39]:

# Create the DataFrame
df = pd.DataFrame({
    'Age': age_values,
    'Gender': gender_values,
    'Concerns': concerns_values,
    'DarkPatches': dark_patches_values,
    'DarkSpots': dark_spots_values,
    'Tanned': tanned_values,
    'FineLine': fine_line_values,
    'Wrinkles': wrinkles_values,
    'Beard': beard_values,
    'SensitiveSkin': sensitive_skin,
    'SkinIssues': skin_issues
})

# Display the first few rows of the dataset
print(df.head())

# Save the dataset to a CSV file
df.to_excel('skinMain2.xlsx', index=False)


   Age  Gender Concerns DarkPatches       DarkSpots Tanned FineLine Wrinkles  \
0   51    Male      Tan         Yes  No/Less Than 5    Yes   No/Few      Yes   
1   50  Female      Tan         Yes     More Than 5     No   No/Few      Yes   
2   62    Male      Tan          No  No/Less Than 5     No     Deep      Yes   
3   46    Male     Acne         Yes     More Than 5     No   No/Few       No   
4   41    Male     Acne          No     More Than 5     No   No/Few       No   

  Beard  SensitiveSkin                                         SkinIssues  
0    No              0                                          No Issues  
1    No              0                                          No Issues  
2   Yes              0                                          No Issues  
3    No              1  Post-Inflammatory Hyperpigmentation - PIH and ...  
4   Yes              0                                          No Issues  


In [1]:
import pandas as pd
import numpy as np
dataset = pd.read_excel('skinMain.xlsx')
dataset

Age  Gender Concerns DarkPatches       DarkSpots Tanned FineLine  \
0     51    Male      Tan         Yes  No/Less Than 5    Yes   No/Few   
1     50  Female      Tan         Yes     More Than 5     No   No/Few   
2     62    Male      Tan          No  No/Less Than 5     No     Deep   
3     46    Male     Acne         Yes     More Than 5     No   No/Few   
4     41    Male     Acne          No     More Than 5     No   No/Few   
..   ...     ...      ...         ...             ...    ...      ...   
995   53  Female      Tan          No     More Than 5    Yes     Deep   
996   44  Female     Acne         Yes     More Than 5     No   No/Few   
997   19    Male     Acne         Yes     More Than 5    Yes     Deep   
998   49  Female     Acne         Yes     More Than 5     No     Deep   
999   40    Male     Acne         Yes  No/Less Than 5    Yes     Deep   

    Wrinkles Beard  SensitiveSkin  \
0        Yes    No              1   
1        Yes    No              0   
2        Yes   Yes              0   
3         No    No              1   
4         No   Yes              0   
..       ...   ...            ...   
995       No   Yes              1   
996      Yes   Yes              1   
997      Yes   Yes              1   
998       No   Yes              1   
999       No    No              0   

                                            SkinIssues  
0                                            No Issues  
1                                            No Issues  
2                                            No Issues  
3    Post-Inflammatory Hyperpigmentation - PIH and ...  
4                                            No Issues  
..                                                 ...  
995                      Hyperpigmentation and Tanning  
996  Post-Inflammatory Hyperpigmentation - PIH and ...  
997  Post-Inflammatory Hyperpigmentation - PIH and ...  
998  Post-Inflammatory Hyperpigmentation - PIH and ...  
999                                          No Issues  

[1000 rows x 11 columns]

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

dataset['Gender'] = le.fit_transform(dataset['Gender'])
dataset['Concerns'] = le.fit_transform(dataset['Concerns'])
dataset['DarkPatches'] = le.fit_transform(dataset['DarkPatches'])
dataset['DarkSpots'] = le.fit_transform(dataset['DarkSpots'])
dataset['Tanned'] = le.fit_transform(dataset['Tanned'])
dataset['FineLine'] = le.fit_transform(dataset['FineLine'])
dataset['Wrinkles'] = le.fit_transform(dataset['Wrinkles'])
dataset['Beard'] = le.fit_transform(dataset['Beard'])

In [3]:
dataset

Age  Gender  Concerns  DarkPatches  DarkSpots  Tanned  FineLine  \
0     51       1         1            1          1       1         1   
1     50       0         1            1          0       0         1   
2     62       1         1            0          1       0         0   
3     46       1         0            1          0       0         1   
4     41       1         0            0          0       0         1   
..   ...     ...       ...          ...        ...     ...       ...   
995   53       0         1            0          0       1         0   
996   44       0         0            1          0       0         1   
997   19       1         0            1          0       1         0   
998   49       0         0            1          0       0         0   
999   40       1         0            1          1       1         0   

     Wrinkles  Beard  SensitiveSkin  \
0           1      0              1   
1           1      0              0   
2           1      1              0   
3           0      0              1   
4           0      1              0   
..        ...    ...            ...   
995         0      1              1   
996         1      1              1   
997         1      1              1   
998         0      1              1   
999         0      0              0   

                                            SkinIssues  
0                                            No Issues  
1                                            No Issues  
2                                            No Issues  
3    Post-Inflammatory Hyperpigmentation - PIH and ...  
4                                            No Issues  
..                                                 ...  
995                      Hyperpigmentation and Tanning  
996  Post-Inflammatory Hyperpigmentation - PIH and ...  
997  Post-Inflammatory Hyperpigmentation - PIH and ...  
998  Post-Inflammatory Hyperpigmentation - PIH and ...  
999                                          No Issues  

[1000 rows x 11 columns]

In [4]:
x = dataset.iloc[:, 0:9].values
x

array([[51,  1,  1, ...,  1,  1,  0],
       [50,  0,  1, ...,  1,  1,  0],
       [62,  1,  1, ...,  0,  1,  1],
       ...,
       [19,  1,  0, ...,  0,  1,  1],
       [49,  0,  0, ...,  0,  0,  1],
       [40,  1,  0, ...,  0,  0,  0]])

In [5]:
y1 = dataset.iloc[:, 9:10].values
y1

array([[ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x, y1, test_size=0.2,random_state=1)

In [7]:
x_train[3]

array([38,  1,  0,  0,  1,  1,  1,  0,  0])

In [8]:
x_test[0]

array([31,  0,  0,  1,  0,  1,  0,  0,  1])

In [9]:
y_train

array([[ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 0],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],

In [10]:
y_test

array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
    

In [11]:
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

model1 = LogisticRegression()
model1.fit(x_train, y_train)
# Predict Y values based on X
y_pred = model1.predict(x_test)
print(y_pred)


[1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0
 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 1
 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0
 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1]


/home/md__nehal__/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/md__nehal__/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print(cm)

print(ac)

[[133   1]
 [  8  58]]
0.955


In [13]:
y_class = dataset.iloc[:, 10:].values
y_class

array([['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['Post-Inflammatory Hyperpigmentation - PIH and Acne'],
       ['No Issues'],
       ['No Issues'],
       ['Hyperpigmentation and Tanning'],
       ['No Issues'],
       ['Post-Inflammatory Hyperpigmentation - PIH and Acne'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['Hyperpigmentation and Tanning'],
       ['No Issues'],
       ['No Issues'],
       ['Hyperpigmentation and Tanning'],
       ['Hyperpigmentation and Tanning'],
       ['No Issues'],
       ['Hyperpigmentation and Tanning'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['Post-Inflammatory Hyperpigmentation - PIH and Acne'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['No Issues'],
       ['Post-Inflammatory Hyperpigmentation - PIH and Acne'],
       ['No Issues'],
       ['P

In [14]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(x, y_class, test_size=0.2,random_state=1)

# np.size(y_class)
for i in range (0,30):
    print(y_train[i])

[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[1]
[1]
[0]
[0]
[1]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[1]
[0]
[1]


In [15]:
from sklearn.neighbors import KNeighborsClassifier

k = 5  # The number of neighbors (you can adjust this)
model2 = KNeighborsClassifier(n_neighbors=k)
model2.fit(x_train1, y_train1)

/home/md__nehal__/anaconda3/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [16]:
y_pred1 = model2.predict(x_test)

In [17]:
cm1 = confusion_matrix(y_test1, y_pred1)
ac1 = accuracy_score(y_test1, y_pred1)

print(cm1)

print(ac1)

[[ 16  18   1]
 [  2 140   0]
 [  9   6   8]]
0.82


# Model Dumping


In [140]:
import pickle
pickle.dump(model1,open('model_sensitive.pkl', 'wb'))
pickle.dump(model2,open('model_problem.pkl', 'wb'))

In [141]:
pickle.dump(model1,open('model_sensitive.pkl', 'wb'))

In [156]:
pickle.dump(model2,open('model_problem.pkl', 'wb'))

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score